<section class="images" style="display: flex; flex-wrap: wrap; justify-content: center; gap: 20px;">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/1.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/3.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/4.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/2.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/5.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/6.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/7.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/8.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/9.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/10.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/11.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/12.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/13.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/14.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/15.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/16.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/17.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/18.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/19.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/20.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/21.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/22.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/23.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/24.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/25.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/26.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/27.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/28.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/29.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/30-fehler.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/31.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/32.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/33.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/34.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/35.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/36.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/37.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/38.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/39.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/40.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/41.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/42.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/43.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/44.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/45.svg' ?>" alt="">
	<img style="width: 120px; height: 120px" src="<?php echo URI . IMG . 'mid/46.svg' ?>" alt="">
</section>